apiVersion: v1
kind: Service
metadata:
  name: gitops-app
  namespace: gitops
spec:
  type: NodePort
  selector:
    app: gitops-app
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080

