name: Auto Demo

on:
  push:
    branches: [main]

permissions:
  contents: write   # ⭐ VERY IMPORTANT FIX

jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Modify file
        run: |
          echo "// updated at $(date)" >> app/backend/server.js

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "auto update"
          git push